### PR TITLE
Added CWTOutput class to fix the issues with the new main cwt method.…

### LINKED ISSUE #18: CWT Line 12
CWT generates an array with 0's in every other position likely stemming from FixOutputArray.

### PR DESCRIPTION
**Pull request by avcarr2**
… Then I fixed all the tests

* Removed several tests that were either not necessary. 
* Commented out a test that needs updating.
* Removed a method that was deprecated with the new CWT method.

### CODE REVIEW

File: FCWTAPI/CWTObject.cs [hunk 1]
```diff
@@ -86,6 +86,20 @@ public void SplitRealAndImaginary(CWTComponent comp, out double[,]? realCwt, out
...
+                    return cwtOutput.RealArray; 
+                case CWTComponent.Imaginary:
+                    return cwtOutput.ImagArray; 
+                case CWTComponent.Both:
+                    throw new NotImplementedException("CWTComponent.Both not implemented for this overload."); 
+                default:
+                    return null;
+            }
+        }
         private double[,] GetComponent(CWTComponent comp, double[,] originalArray)
```
Comment (zdanaceau) [inline FCWTAPI/CWTObject.cs]: Is the intention for this method to be removed/rendered obsolete?

File: FCWTAPI/CWTObject.cs [hunk 2]
```diff
@@ -86,6 +86,20 @@ public void SplitRealAndImaginary(CWTComponent comp, out double[,]? realCwt, out
                     break;
             }
         }
+        public double[,]? GetComponent(CWTComponent comp, CWTOutput cwtOutput)
```
Comment (zdanaceau) [inline FCWTAPI/CWTObject.cs]: If the only function of this method to return Real, Imaginary or Both as as a single array, wouldn't it make more sense to just have a method to get both components in a single array since SplitRealAndImaginary already gets a double[ , ] corresponding to the real and imaginary components?

File: FCWTAPI/CWTObject.cs [hunk 3]
```diff
@@ -145,26 +165,17 @@ public void SplitRealAndImaginary(CWTComponent comp, out double[,]? realCwt, out
...
-                    outputArray[i , j] = modPoint;
+                    output[i, j] = Math.Sqrt(Math.Pow(OutputCWT.RealArray[i, j], 2) + Math.Pow(OutputCWT.ImagArray[i, j], 2)); 
                 }
-                originalIndex += 2;
-                
             }
-            return outputArray;
+            return output;
         }
         /// <summary>
```
Comment (zdanaceau) [inline FCWTAPI/CWTObject.cs:81]: Can you add a comment in here stating that this method of calculating the phase may be not great so that we remember later down the road?

File: FCWTAPI/CWTOutput.cs [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+    }
+    public static class CWTOutputExtensions
+    {
+        public static int GetLength(this CWTOutput cwtoutput, int dimension)
+        {
+            switch (dimension)
+            {
+                case 0: return cwtoutput.RealArray.GetLength(0);
+                case 1: return cwtoutput.RealArray.GetLength(1);
+                default: return -1;
```
Comment (zdanaceau) [inline FCWTAPI/CWTOutput.cs]: Would it be better to throw an exception here to make it more traceable if an int != 0 or 1 was entered?

File: FCWTAPI/CWTObject.cs [hunk 5]
```diff
@@ -230,10 +235,10 @@ public void CalculateTimeAxis()
             {
                 throw new ArgumentNullException("OutputCWT", "Output CWT must be calculated prior to calculating a time axis for it");
             }
-            double [] timeArray = new double[OutputCWT.GetLength(1)];
+            double [] timeArray = new double[OutputCWT.RealArray.GetLength(1)];
             double timeStep = 1 / (double)SamplingRate;
             double currentTime = 0;
-            for (int i = 0; i < OutputCWT.GetLength(1); i++)
+            for (int i = 0; i < OutputCWT.RealArray.GetLength(1); i++)
```
Comment (zdanaceau) [inline FCWTAPI/CWTObject.cs:142]: I suspect that this may be the inefficiency since this for loop is going to require that OutputCWT.RealArray.GetLength(1) will have to be calculated for every i, and given typical data sizes this will lead to 10's to hundreds of thousands of unnecessary calculations.

File: TestFCWTAPI/CWTObjectTests.cs [hunk 6]
```diff
@@ -73,26 +74,26 @@ public static void TestModulusCalculation()
...
-            CWTObject noCWT = new CWTObject(cosine, 1, 6, 200, (float)(2 * Math.PI), 4, false);
-            Assert.Throws<ArgumentNullException>(() => noCWT.PhaseCalculation());
-            CWTObject cosineCWT = new CWTObject(cosine, 1, 6, 200, (float)(2 * Math.PI), 4, false);
-            cosineCWT.PerformCWT();
-            cosineCWT.SplitRealAndImaginary(CWTObject.CWTComponent.Both, out double[,] realCwt, out double[,] imagCwt);
-            double[,] testPhase = cosineCWT.PhaseCalculation();
-            double testPoint = Math.Atan(imagCwt[32, 32] / realCwt[32, 32]);
-            Assert.AreEqual(testPoint, testPhase[32, 32], 0.001);
-        }
+        //[Test]
```
Comment (zdanaceau) [inline TestFCWTAPI/CWTObjectTests.cs:54]: Why did you comment this out?

**Review by zdanaceau — CHANGES_REQUESTED** [review]
See the comment on the GetComponent method and fix what I believe is the inefficiency in the CalculateTimeAxis function.
